#!/bin/bash
#
#SBATCH --job-name=test
#
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --mem=32000
#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --constraint=cuda75|cuda61
#SBATCH --output=out/test_learner.out

source activate gscan

python -u -m teacher_learner_training --mode=test --data_directory=data/compositional_splits --attention_type=bahdanau --no_auxiliary_task --conditional_attention --output_directory=out_learner_both --splits=test,visual_easier,visual,situational_1,situational_2,contextual,adverb_1,adverb_2 --max_decoding_steps=120 --max_testing_examples 2000 --test_checkpoints out_learner_both/checkpoint_iter_192053.pth.tar out_learner_both/checkpoint_iter_192100.pth.tar out_learner_both/checkpoint_iter_192200.pth.tar out_learner_both/checkpoint_iter_192300.pth.tar out_learner_both/checkpoint_iter_192400.pth.tar out_learner_both/checkpoint_iter_192500.pth.tar out_learner_both/checkpoint_iter_192600.pth.tar out_learner_both/checkpoint_iter_192700.pth.tar out_learner_both/checkpoint_iter_192800.pth.tar out_learner_both/checkpoint_iter_192900.pth.tar out_learner_both/checkpoint_iter_193000.pth.tar out_learner_both/checkpoint_iter_194000.pth.tar out_learner_both/checkpoint_iter_195000.pth.tar out_learner_both/checkpoint_iter_196000.pth.tar out_learner_both/checkpoint_iter_197000.pth.tar out_learner_both/checkpoint_iter_198000.pth.tar out_learner_both/checkpoint_iter_199000.pth.tar out_learner_both/checkpoint_iter_200000.pth.tar
#python -u -m teacher_learner_training --mode=test --data_directory=data/compositional_splits --attention_type=bahdanau --no_auxiliary_task --conditional_attention --output_directory=out_learner_t_l_reset_optimizer --splits=test,visual_easier,visual,situational_1,situational_2,contextual,adverb_1,adverb_2 --max_decoding_steps=120 --max_testing_examples 2000 --test_checkpoints out_learner_t_l_reset_optimizer/checkpoint_iter_210000.pth.tar out_learner_t_l_reset_optimizer/checkpoint_iter_220000.pth.tar out_learner_t_l_reset_optimizer/checkpoint_iter_230000.pth.tar out_learner_t_l_reset_optimizer/checkpoint_iter_240000.pth.tar out_learner_t_l_reset_optimizer/checkpoint_iter_250000.pth.tar out_learner_t_l_reset_optimizer/checkpoint_iter_260000.pth.tar out_learner_t_l_reset_optimizer/checkpoint_iter_270000.pth.tar

#python -u -m teacher_learner_training --mode=test --data_directory=data/compositional_splits --attention_type=bahdanau --no_auxiliary_task --conditional_attention --output_directory=out_learner_t_l_small_lr --splits=test,visual_easier,visual,situational_1,situational_2,contextual,adverb_1,adverb_2 --max_decoding_steps=120 --max_testing_examples 2000 --test_checkpoints out_learner_t_l_small_lr/checkpoint_iter_192100.pth.tar out_learner_t_l_small_lr/checkpoint_iter_192200.pth.tar out_learner_t_l_small_lr/checkpoint_iter_192300.pth.tar out_learner_t_l_small_lr/checkpoint_iter_192400.pth.tar out_learner_t_l_small_lr/checkpoint_iter_192500.pth.tar out_learner_t_l_small_lr/checkpoint_iter_192600.pth.tar out_learner_t_l_small_lr/checkpoint_iter_192700.pth.tar out_learner_t_l_small_lr/checkpoint_iter_192800.pth.tar out_learner_t_l_small_lr/checkpoint_iter_192900.pth.tar out_learner_t_l_small_lr/checkpoint_iter_193000.pth.tar out_learner_t_l_small_lr/checkpoint_iter_194000.pth.tar out_learner_t_l_small_lr/checkpoint_iter_195000.pth.tar out_learner_t_l_small_lr/checkpoint_iter_196000.pth.tar out_learner_t_l_small_lr/checkpoint_iter_197000.pth.tar out_learner_t_l_small_lr/checkpoint_iter_198000.pth.tar out_learner_t_l_small_lr/checkpoint_iter_199000.pth.tar out_learner_t_l_small_lr/checkpoint_iter_200000.pth.tar out_learner_t_l_small_lr/checkpoint_iter_210000.pth.tar out_learner_t_l_small_lr/checkpoint_iter_220000.pth.tar out_learner_t_l_small_lr/checkpoint_iter_230000.pth.tar out_learner_t_l_small_lr/checkpoint_iter_240000.pth.tar out_learner_t_l_small_lr/checkpoint_iter_250000.pth.tar out_learner_t_l_small_lr/checkpoint_iter_260000.pth.tar out_learner_t_l_small_lr/checkpoint_iter_270000.pth.tar

#python -u -m teacher_learner_training --mode=test --data_directory=data/compositional_splits --attention_type=bahdanau --no_auxiliary_task --conditional_attention --output_directory=out_learner_l_t_l --splits=test,visual_easier,visual,situational_1,situational_2,contextual,adverb_1,adverb_2 --max_decoding_steps=120 --max_testing_examples 2000 --test_checkpoints out_learner_l_t_l/checkpoint_iter_192300.pth.tar out_learner_l_t_l/checkpoint_iter_192400.pth.tar out_learner_l_t_l/checkpoint_iter_192500.pth.tar out_learner_l_t_l/checkpoint_iter_192600.pth.tar out_learner_l_t_l/checkpoint_iter_192700.pth.tar out_learner_l_t_l/checkpoint_iter_192800.pth.tar out_learner_l_t_l/checkpoint_iter_192900.pth.tar out_learner_l_t_l/checkpoint_iter_193000.pth.tar out_learner_l_t_l/checkpoint_iter_194000.pth.tar out_learner_l_t_l/checkpoint_iter_195000.pth.tar out_learner_l_t_l/checkpoint_iter_196000.pth.tar out_learner_l_t_l/checkpoint_iter_197000.pth.tar out_learner_l_t_l/checkpoint_iter_198000.pth.tar out_learner_l_t_l/checkpoint_iter_199000.pth.tar out_learner_l_t_l/checkpoint_iter_200000.pth.tar out_learner_l_t_l/checkpoint_iter_210000.pth.tar
